name: Python package
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          python_version: "3.9"
          poetry_version: "==1.4.2" # (PIP version specifier syntax)
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          allow_poetry_pre_release: "yes"
          ignore_dev_requirements: "yes"
